create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists role text not null default 'user';
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('user', 'admin'));

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12, 2) not null check (price >= 0),
  image text,
  category text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text not null,
  message text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved')),
  created_at timestamptz not null default now()
);

create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('service', 'partner', 'blog', 'slider', 'project', 'team')),
  title text not null,
  description text,
  image text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.contact_messages enable row level security;
alter table public.content_items enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "Public products are readable" on public.products;
create policy "Public products are readable" on public.products for select using (true);

drop policy if exists "Anyone can submit contact messages" on public.contact_messages;
create policy "Anyone can submit contact messages" on public.contact_messages for insert with check (true);

drop policy if exists "Users can read their profile" on public.profiles;
create policy "Users can read their profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can manage contact messages" on public.contact_messages;
create policy "Admins can manage contact messages" on public.contact_messages for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Public content is readable" on public.content_items;
create policy "Public content is readable" on public.content_items for select using (true);

drop policy if exists "Admins can manage content" on public.content_items;
create policy "Admins can manage content" on public.content_items for all using (public.is_admin()) with check (public.is_admin());

drop trigger if exists on_auth_user_created on auth.users;
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name');
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.products (id, name, price, image, category)
values
  (1, 'Networking Cable', 25.00, '/products/product1.jpg', 'Networking'),
  (2, 'Wireless Router', 80.00, '/products/product2.jpg', 'Networking'),
  (3, 'Construction Per Work', 750.00, '/products/product3.jpg', 'Computers'),
  (4, 'Ethernet Switch', 45.00, '/products/product5.jpg', 'Networking'),
  (5, 'Construction Per Work', 1200.00, '/products/product6.jpg', 'Computers'),
  (6, 'Multi Mode FSP', 180.00, '/products/product9.jpg', 'Networking')
on conflict (id) do update set name = excluded.name, price = excluded.price, image = excluded.image, category = excluded.category;

select setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1));

-- Promote a trusted account after it has registered in the app:
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'admin@example.com');
