-- SysNet Technologies Database Schema

-- 1. Profiles Table
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  phone text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists role text not null default 'user';
alter table public.profiles add column if not exists phone text;
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('user', 'admin'));

-- 2. Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12, 2) not null check (price >= 0),
  image text,
  category text not null,
  description text,
  in_stock boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists description text;
alter table public.products add column if not exists in_stock boolean not null default true;

-- 3. Contact Messages Table (with Admin Replies)
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text not null,
  message text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved')),
  admin_reply text,
  replied_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.contact_messages add column if not exists admin_reply text;
alter table public.contact_messages add column if not exists replied_at timestamptz;

-- 4. Content Items Table (Services, Partners, Blogs, Slider pictures, Projects, Team)
create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('service', 'partner', 'blog', 'slider', 'project', 'team')),
  title text not null,
  subtitle text,
  slug text,
  description text,
  content text,
  image text,
  category text,
  extra_data jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.content_items add column if not exists subtitle text;
alter table public.content_items add column if not exists slug text;
alter table public.content_items add column if not exists content text;
alter table public.content_items add column if not exists category text;
alter table public.content_items add column if not exists extra_data jsonb default '{}'::jsonb;

-- 5. Orders / Cart Inquiries Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_name text,
  user_email text not null,
  user_phone text,
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(12, 2) not null default 0,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'cancelled')),
  notes text,
  created_at timestamptz not null default now()
);

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.contact_messages enable row level security;
alter table public.content_items enable row level security;
alter table public.orders enable row level security;

-- Admin Helper Function
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- RLS Policies: Products
drop policy if exists "Public products are readable" on public.products;
create policy "Public products are readable" on public.products for select using (true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());

-- RLS Policies: Contact Messages
drop policy if exists "Anyone can submit contact messages" on public.contact_messages;
create policy "Anyone can submit contact messages" on public.contact_messages for insert with check (true);

drop policy if exists "Users can read own contact messages" on public.contact_messages;
create policy "Users can read own contact messages" on public.contact_messages for select using (
  auth.uid() is not null and email = (select email from auth.users where id = auth.uid())
);

drop policy if exists "Admins can manage contact messages" on public.contact_messages;
create policy "Admins can manage contact messages" on public.contact_messages for all using (public.is_admin()) with check (public.is_admin());

-- RLS Policies: Profiles
drop policy if exists "Users can read their profile" on public.profiles;
create policy "Users can read their profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

-- RLS Policies: Content Items
drop policy if exists "Public content is readable" on public.content_items;
create policy "Public content is readable" on public.content_items for select using (true);

drop policy if exists "Admins can manage content" on public.content_items;
create policy "Admins can manage content" on public.content_items for all using (public.is_admin()) with check (public.is_admin());

-- RLS Policies: Orders
drop policy if exists "Users can read own orders" on public.orders;
create policy "Users can read own orders" on public.orders for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can insert orders" on public.orders;
create policy "Users can insert orders" on public.orders for insert with check (true);

drop policy if exists "Admins can manage orders" on public.orders;
create policy "Admins can manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());

-- Auth trigger to create profile upon registration
drop trigger if exists on_auth_user_created on auth.users;
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data ->> 'full_name', coalesce(new.raw_user_meta_data ->> 'role', 'user'))
  on conflict (id) do update set
    full_name = coalesce(excluded.full_name, profiles.full_name),
    role = coalesce(excluded.role, profiles.role);
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Seed initial products
insert into public.products (id, name, price, image, category, description)
values
  (1, 'Networking Cable', 25.00, '/products/product1.jpg', 'Networking', 'High speed shielded Cat6 RJ45 patch cable for durable connectivity.'),
  (2, 'Wireless Router', 80.00, '/products/product2.jpg', 'Networking', 'Dual-band Gigabit wireless router with advanced encryption and coverage.'),
  (3, 'Construction Per Work', 750.00, '/products/product3.jpg', 'Computers', 'Professional computer and workstation deployment package.'),
  (4, 'Ethernet Switch', 45.00, '/products/product5.jpg', 'Networking', '8-port Gigabit unmanaged desktop switch with auto MDI/MDIX.'),
  (5, 'Enterprise Server Rack', 1200.00, '/products/product6.jpg', 'Computers', 'Heavy duty 42U server cabinet with cooling fans and cable management.'),
  (6, 'Multi Mode FSP', 180.00, '/products/product9.jpg', 'Networking', 'Optical multi-mode fiber transceiver module for ultra-fast backbone data.')
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  image = excluded.image,
  category = excluded.category,
  description = excluded.description;

select setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1));

-- Seed content currently presented by the website so it is available to admins.
insert into public.content_items
  (content_type, title, subtitle, slug, description, content, image, category, extra_data)
select seed.content_type, seed.title, seed.subtitle, seed.slug, seed.description,
  seed.content, seed.image, seed.category, seed.extra_data
from (
  values
    ('slider', 'Doing with Excellence.', null, null,
      'To define quality, cultivate unrivaled customer loyalty, and provide comprehensive solutions to customers'' demands.',
      null, '/images/hero/hero1.webp', null,
      '{"link":"/contact","buttonText":"Contact Us"}'::jsonb),
    ('slider', 'Technology Built for Growth.', null, null,
      'Secure networks, smarter systems, and reliable support that keep organizations moving forward.',
      null, '/images/hero/hero2.webp', null,
      '{"link":"/services","buttonText":"Explore Services"}'::jsonb),
    ('slider', 'Your Trusted IT Partner.', null, null,
      'From design to deployment, we help businesses and institutions build resilient digital infrastructure.',
      null, '/images/hero/hero3.webp', null,
      '{"link":"/about","buttonText":"About SysNet"}'::jsonb),
    ('service', 'Computing', null, 'computing',
      'Robust computing infrastructure and dependable support for organizations that depend on reliable digital operations.',
      'Computing is an advanced IT service offered by SysNet Technologies. Our customers for this kind of service are typically factories and international NGOs, organizations that require dependable, professionally managed computing infrastructure to support their operations.',
      '/images/services/service1.jpg', null,
      '{"features":["Server installation and configuration","Datacenter facilities","System maintenance and support"]}'::jsonb),
    ('service', 'Solutions', null, 'solutions',
      'Tailor-made technology solutions that simplify workflows, increase productivity, and support business growth.',
      'Solutions is a customized technology service designed to improve efficiency, productivity, and overall business performance for our clients. We deliver practical and scalable systems for organizations looking to streamline operations and improve service delivery.',
      '/images/services/service2.jpg', null,
      '{"features":["Custom software and systems integration","Business process automation","Technology needs assessment and planning"]}'::jsonb),
    ('service', 'Network & Security', null, 'network-and-security',
      'Secure, scalable networking and protection strategies designed to keep critical systems stable and resilient.',
      'Computer Networking and Security focuses on designing, installing, managing, and protecting computer networks to ensure reliable communication and data security. We support businesses and institutions with secure and high-performing infrastructure.',
      '/images/services/service3.jpg', null,
      '{"features":["Network design and installation","Firewall and cybersecurity setup","Network monitoring and maintenance","Data security and protection"]}'::jsonb),
    ('service', 'Sales', null, 'sales',
      'Access to trusted hardware, software, and IT products that match your operational and budget requirements.',
      'Sales provides technology products, devices, and software solutions to meet customer requirements. We supply reliable hardware, networking equipment, and software for business and institutional use.',
      '/images/services/service4.jpg', null,
      '{"features":["Computers and office equipment","Networking hardware and cabling","Licensed software solutions"]}'::jsonb),
    ('service', 'Consultancy', null, 'consultancy',
      'Strategic guidance to help businesses plan, invest, and modernize with confidence.',
      'Consultancy provides professional technology advice and guidance to help businesses make better decisions about their IT infrastructure, systems, and digital strategies. We support organizations before they commit to major technology investments.',
      '/images/services/service4.jpg', null,
      '{"features":["IT infrastructure planning and assessment","Digital transformation strategy","Technology vendor and solution advisory"]}'::jsonb),
    ('partner', 'OLWAY', null, null, null, null, '/images/partners/partner1.jpg', null, '{"website":"https://example.com"}'::jsonb),
    ('partner', 'PMC', null, null, null, null, '/images/partners/partner2.jpg', null, '{"website":"https://example.com"}'::jsonb),
    ('partner', 'Addis Continental', null, null, null, null, '/images/partners/partner3.jpg', null, '{"website":"https://example.com"}'::jsonb),
    ('partner', 'SysNet Client', null, null, null, null, '/images/partners/partner4.jpg', null, '{"website":"https://example.com"}'::jsonb),
    ('partner', 'Institutional Partner', null, null, null, null, '/images/partners/partner5.jpg', null, '{"website":"https://example.com"}'::jsonb),
    ('blog', 'Building Resilient Enterprise Networks in 2026', 'Abel Samuel', 'building-secure-enterprise-networks',
      'Discover essential architectural principles and cybersecurity strategies to protect modern institutional infrastructure.',
      'In today''s interconnected landscape, enterprise networks are the backbone of institutional operations. From high-throughput fiber uplinks to next-generation firewall policies, designing resilience into every layer is critical.',
      '/images/services/service3.jpg', 'Networking & Security', '{"date":"August 24, 2026"}'::jsonb),
    ('blog', 'How Smart IT Procurement Reduces Downtime', 'Nahom Berhanu', 'streamlining-it-procurement',
      'Selecting high quality hardware and certified networking gear saves organizations significant cost and troubleshooting time.',
      'Choosing the right IT equipment is more than comparing specs on a sheet. It involves lifecycle planning, warranty support, and compatibility with your existing environment.',
      '/images/services/service4.jpg', 'Hardware & Sales', '{"date":"August 18, 2026"}'::jsonb),
    ('blog', 'Custom Software Solutions for Growing Businesses', 'Frehiwot Endalkachew', 'custom-software-business-growth',
      'Tailor-made portals and database workflows empower teams to scale without operational bottlenecks.',
      'Off-the-shelf software often leaves gaps in reporting, inventory tracking, and client self-service. Custom web applications bridge these gaps by aligning software directly to your business processes.',
      '/images/services/service2.jpg', 'Digital Solutions', '{"date":"August 10, 2026"}'::jsonb),
    ('project', 'Network Installation', 'OLWAY Petroleum', null,
      'Network installation covering 80 plus nodes for a reliable and scalable enterprise connectivity solution.',
      null, '/images/projects/project1.png', 'Networking', '{"year":"2024"}'::jsonb),
    ('project', 'Website Development', 'PMC Ethiopia', null,
      'Modern website development tailored to strengthen digital presence and business communication.',
      null, '/images/projects/project2.jpg', 'Web & Software', '{"year":"2023"}'::jsonb),
    ('project', 'Network Installation', 'Addis Continental Institute', null,
      'Network installation of 560 nodes designed for a large-scale, high-performance institutional infrastructure.',
      null, '/images/projects/project3.jpg', 'Enterprise Infrastructure', '{"year":"2023"}'::jsonb),
    ('project', 'Network Installation', 'Enterprise Solutions Ltd', null,
      'Network installation of 50 nodes combined with web administration for dependable operational support.',
      null, '/images/projects/project4.jpg', 'Networking & Admin', '{"year":"2022"}'::jsonb),
    ('project', 'Website Development', 'Financial Services Corp', null,
      'Website development focused on professional online presence, accessibility, and business growth support.',
      null, '/images/projects/project5.jpg', 'Web & Portals', '{"year":"2022"}'::jsonb),
    ('team', 'Abel Samuel', 'General Manager', null,
      'Executive technology leader with over a decade of IT infrastructure management experience.',
      null, '/images/team/team1.png', null, '{}'::jsonb),
    ('team', 'Frehiwot Endalkachew', 'Co-Founder and Marketing Manager', null,
      'Strategic partner leading brand growth and institutional client relations.',
      null, '/images/team/team2.jpg', null, '{}'::jsonb),
    ('team', 'Nahom Berhanu', 'Web Developer', null,
      'Full stack engineer specializing in robust web applications and cloud integrations.',
      null, '/images/team/team3.jpg', null, '{}'::jsonb),
    ('team', 'Kirubel E.', 'Support Specialist', null,
      'Certified systems specialist providing rapid support and maintenance across enterprise networks.',
      null, '/images/team/team4.jpg', null, '{}'::jsonb)
) as seed(content_type, title, subtitle, slug, description, content, image, category, extra_data)
where not exists (
  select 1 from public.content_items existing
  where existing.content_type = seed.content_type
    and existing.title = seed.title
);
