-- SysNet Technologies Database Schema

-- 1. Profiles Table
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  phone text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists role text not null default 'user';
alter table public.profiles add column if not exists phone text;
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('user', 'admin'));

-- 2. Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12, 2) not null check (price >= 0),
  image text,
  category text not null,
  description text,
  in_stock boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists description text;
alter table public.products add column if not exists in_stock boolean not null default true;

-- 3. Contact Messages Table (with Admin Replies)
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text not null,
  message text not null,
  status text not null default 'new' check (status in ('new', 'in_progress', 'resolved')),
  admin_reply text,
  replied_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.contact_messages add column if not exists admin_reply text;
alter table public.contact_messages add column if not exists replied_at timestamptz;

-- 4. Content Items Table (Services, Partners, Blogs, Slider pictures, Projects, Team)
create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('service', 'partner', 'blog', 'slider', 'project', 'team')),
  title text not null,
  subtitle text,
  slug text,
  description text,
  content text,
  image text,
  category text,
  extra_data jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.content_items add column if not exists subtitle text;
alter table public.content_items add column if not exists slug text;
alter table public.content_items add column if not exists content text;
alter table public.content_items add column if not exists category text;
alter table public.content_items add column if not exists extra_data jsonb default '{}'::jsonb;

-- 5. Orders / Cart Inquiries Table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_name text,
  user_email text not null,
  user_phone text,
  items jsonb not null default '[]'::jsonb,
  total_amount numeric(12, 2) not null default 0,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'cancelled')),
  notes text,
  created_at timestamptz not null default now()
);

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.contact_messages enable row level security;
alter table public.content_items enable row level security;
alter table public.orders enable row level security;

-- Admin Helper Function
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- RLS Policies: Products
drop policy if exists "Public products are readable" on public.products;
create policy "Public products are readable" on public.products for select using (true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());

-- RLS Policies: Contact Messages
drop policy if exists "Anyone can submit contact messages" on public.contact_messages;
create policy "Anyone can submit contact messages" on public.contact_messages for insert with check (true);

drop policy if exists "Users can read own contact messages" on public.contact_messages;
create policy "Users can read own contact messages" on public.contact_messages for select using (
  auth.uid() is not null and email = (select email from auth.users where id = auth.uid())
);

drop policy if exists "Admins can manage contact messages" on public.contact_messages;
create policy "Admins can manage contact messages" on public.contact_messages for all using (public.is_admin()) with check (public.is_admin());

-- RLS Policies: Profiles
drop policy if exists "Users can read their profile" on public.profiles;
create policy "Users can read their profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles" on public.profiles for all using (public.is_admin()) with check (public.is_admin());

-- RLS Policies: Content Items
drop policy if exists "Public content is readable" on public.content_items;
create policy "Public content is readable" on public.content_items for select using (true);

drop policy if exists "Admins can manage content" on public.content_items;
create policy "Admins can manage content" on public.content_items for all using (public.is_admin()) with check (public.is_admin());

-- RLS Policies: Orders
drop policy if exists "Users can read own orders" on public.orders;
create policy "Users can read own orders" on public.orders for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Users can insert orders" on public.orders;
create policy "Users can insert orders" on public.orders for insert with check (true);

drop policy if exists "Admins can manage orders" on public.orders;
create policy "Admins can manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());

-- Auth trigger to create profile upon registration
drop trigger if exists on_auth_user_created on auth.users;
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data ->> 'full_name', coalesce(new.raw_user_meta_data ->> 'role', 'user'))
  on conflict (id) do update set
    full_name = coalesce(excluded.full_name, profiles.full_name),
    role = coalesce(excluded.role, profiles.role);
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Seed initial products
insert into public.products (id, name, price, image, category, description)
values
  (1, 'Networking Cable', 25.00, '/products/product1.jpg', 'Networking', 'High speed shielded Cat6 RJ45 patch cable for durable connectivity.'),
  (2, 'Wireless Router', 80.00, '/products/product2.jpg', 'Networking', 'Dual-band Gigabit wireless router with advanced encryption and coverage.'),
  (3, 'Construction Per Work', 750.00, '/products/product3.jpg', 'Computers', 'Professional computer and workstation deployment package.'),
  (4, 'Ethernet Switch', 45.00, '/products/product5.jpg', 'Networking', '8-port Gigabit unmanaged desktop switch with auto MDI/MDIX.'),
  (5, 'Enterprise Server Rack', 1200.00, '/products/product6.jpg', 'Computers', 'Heavy duty 42U server cabinet with cooling fans and cable management.'),
  (6, 'Multi Mode FSP', 180.00, '/products/product9.jpg', 'Networking', 'Optical multi-mode fiber transceiver module for ultra-fast backbone data.')
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  image = excluded.image,
  category = excluded.category,
  description = excluded.description;

select setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1));
