"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "../../lib/supabase/client";

type ContentType = "service" | "partner" | "blog" | "slider" | "project" | "team";
type ContentItem = { id: number; content_type: ContentType; title: string; description: string | null; image: string | null };
const sections: Array<[string, ContentType, string]> = [
  ["Services", "service", "New services"], ["Partners", "partner", "New partners"], ["Blogs", "blog", "New blog posts"],
  ["Slider pictures", "slider", "Homepage slider pictures"], ["Latest Projects", "project", "Latest projects"], ["Team Members", "team", "Team members"],
];

export default function AdminDashboard({ name }: { name: string }) {
  const [activeSection, setActiveSection] = useState("Products");
  const [notice, setNotice] = useState("");
  async function signOut() { await createClient().auth.signOut(); window.location.href = "/login"; }
  const selected = sections.find(([title]) => title === activeSection);

  return <div className="min-h-screen bg-slate-100 px-4 py-10"><div className="mx-auto max-w-7xl">
    <div className="flex flex-col gap-5 border-b border-slate-200 pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-600">Administrator workspace</p><h1 className="mt-2 text-4xl font-black text-slate-900">Welcome, {name}</h1><p className="mt-2 text-slate-600">Manage the content and conversations that power SysNet.</p></div><button type="button" onClick={signOut} className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50">Sign out</button></div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[240px_1fr]"><aside className="rounded-2xl bg-slate-900 p-3 text-white"><button type="button" onClick={() => setActiveSection("Products")} className={`mb-2 w-full rounded-xl px-4 py-3 text-left font-bold ${activeSection === "Products" ? "bg-blue-600" : "hover:bg-slate-800"}`}>Products</button>{sections.map(([title, , description]) => <button key={title} type="button" onClick={() => setActiveSection(title)} className={`w-full rounded-xl px-4 py-3 text-left ${activeSection === title ? "bg-blue-600" : "hover:bg-slate-800"}`}><span className="block font-bold">{title}</span><span className="mt-1 block text-xs text-slate-300">{description}</span></button>)}<button type="button" onClick={() => setActiveSection("Messages")} className={`mt-2 w-full rounded-xl px-4 py-3 text-left font-bold ${activeSection === "Messages" ? "bg-blue-600" : "hover:bg-slate-800"}`}>Contact messages</button></aside>
      <section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200 md:p-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-blue-600">Content manager</p><h2 className="mt-2 text-3xl font-black text-slate-900">{activeSection}</h2>{activeSection === "Products" ? <ProductManager setNotice={setNotice} /> : activeSection === "Messages" ? <MessageInbox setNotice={setNotice} /> : selected ? <ContentManager type={selected[1]} setNotice={setNotice} /> : null}{notice ? <p className="mt-5 rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-700">{notice}</p> : null}</section>
    </div>
  </div></div>;
}

function ContentManager({ type, setNotice }: { type: ContentType; setNotice: (value: string) => void }) {
  const [items, setItems] = useState<ContentItem[]>([]); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [image, setImage] = useState("");
  async function load() { const { data } = await createClient().from("content_items").select("id, content_type, title, description, image").eq("content_type", type).order("id", { ascending: false }); setItems(data || []); }
  useEffect(() => { void load(); }, [type]);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const { data, error } = await createClient().from("content_items").insert({ content_type: type, title, description, image }).select("id, content_type, title, description, image").single(); if (error) setNotice(error.message); else { setItems((current) => [data, ...current]); setTitle(""); setDescription(""); setImage(""); setNotice("Item added successfully."); } }
  async function remove(id: number) { const { error } = await createClient().from("content_items").delete().eq("id", id); if (error) setNotice(error.message); else { setItems((current) => current.filter((item) => item.id !== id)); setNotice("Item removed."); } }
  return <div><form onSubmit={add} className="mt-8 grid gap-4 sm:grid-cols-2"><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Title or name" className="rounded-lg border border-slate-300 px-3 py-2.5" /><input value={image} onChange={(event) => setImage(event.target.value)} placeholder="Image path (optional)" className="rounded-lg border border-slate-300 px-3 py-2.5" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Description or article text" className="rounded-lg border border-slate-300 px-3 py-2.5 sm:col-span-2" /><button type="submit" className="rounded-lg bg-blue-600 px-5 py-3 font-bold text-white hover:bg-blue-700 sm:col-span-2">Add item</button></form><ItemList items={items} remove={remove} /></div>;
}

function ProductManager({ setNotice }: { setNotice: (value: string) => void }) { const [items, setItems] = useState<Array<{ id: number; name: string; price: number; category: string }>>([]); const [name, setName] = useState(""); const [price, setPrice] = useState(""); const [category, setCategory] = useState(""); const [image, setImage] = useState("");
  async function load() { const { data } = await createClient().from("products").select("id, name, price, category").order("id", { ascending: false }); setItems(data || []); } useEffect(() => { void load(); }, []);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const { data, error } = await createClient().from("products").insert({ name, price: Number(price), category, image }).select("id, name, price, category").single(); if (error) setNotice(error.message); else { setItems((current) => [data, ...current]); setName(""); setPrice(""); setCategory(""); setImage(""); setNotice("Product added successfully."); } }
  async function remove(id: number) { const { error } = await createClient().from("products").delete().eq("id", id); if (error) setNotice(error.message); else { setItems((current) => current.filter((item) => item.id !== id)); setNotice("Product removed."); } }
  return <div><form onSubmit={add} className="mt-8 grid gap-4 sm:grid-cols-2"><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Product name" className="rounded-lg border border-slate-300 px-3 py-2.5" /><input required min="0" step="0.01" type="number" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="Price" className="rounded-lg border border-slate-300 px-3 py-2.5" /><input required value={category} onChange={(event) => setCategory(event.target.value)} placeholder="Category" className="rounded-lg border border-slate-300 px-3 py-2.5" /><input value={image} onChange={(event) => setImage(event.target.value)} placeholder="Image path" className="rounded-lg border border-slate-300 px-3 py-2.5" /><button type="submit" className="rounded-lg bg-blue-600 px-5 py-3 font-bold text-white hover:bg-blue-700 sm:col-span-2">Add product</button></form><div className="mt-8 space-y-3">{items.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><span><strong>{item.name}</strong><small className="ml-3 text-slate-500">{item.category} · ${Number(item.price).toFixed(2)}</small></span><button type="button" onClick={() => remove(item.id)} className="text-sm font-bold text-red-600">Remove</button></div>)}</div></div>; }

function ItemList({ items, remove }: { items: ContentItem[]; remove: (id: number) => void }) { return <div className="mt-8 space-y-3">{items.length ? items.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-4"><span><strong>{item.title}</strong>{item.description ? <small className="ml-3 text-slate-500">{item.description}</small> : null}</span><button type="button" onClick={() => remove(item.id)} className="shrink-0 text-sm font-bold text-red-600">Remove</button></div>) : <p className="text-slate-500">No items yet.</p>}</div>; }

function MessageInbox({ setNotice }: { setNotice: (value: string) => void }) { const [messages, setMessages] = useState<Array<{ id: number; name: string; email: string; subject: string; message: string; status: string }>>([]); useEffect(() => { void load(); async function load() { const { data } = await createClient().from("contact_messages").select("id, name, email, subject, message, status").order("created_at", { ascending: false }); setMessages(data || []); } }, []); async function updateStatus(id: number, status: string) { const { error } = await createClient().from("contact_messages").update({ status }).eq("id", id); if (error) setNotice(error.message); else { setMessages((current) => current.map((item) => item.id === id ? { ...item, status } : item)); setNotice("Message status updated."); } } return <div className="mt-8 space-y-4">{messages.length ? messages.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-5"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">{item.subject}</h3><select value={item.status} onChange={(event) => updateStatus(item.id, event.target.value)} className="rounded border border-slate-300 px-2 py-1 text-xs"><option value="new">New</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option></select></div><p className="mt-1 text-sm text-slate-500">{item.name} · {item.email}</p><p className="mt-4 leading-6 text-slate-700">{item.message}</p><a href={`mailto:${item.email}?subject=Re: ${encodeURIComponent(item.subject)}`} className="mt-4 inline-block font-bold text-blue-700">Respond by email</a></article>) : <p className="text-slate-500">No contact messages yet.</p>}</div>; }
